services:
  mihomo:
    image: metacubex/mihomo:latest
    container_name: mihomo
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/mihomo-config.yaml:/root/.config/mihomo/config.yaml:ro

  mikrov2ray:
    image: triarh1/mikrov2ray:latest
    container_name: mikrov2ray
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mihomo
